#ifndef CONFIG_H
#define CONFIG_H

#define N_BUZZER 5

#define PIN_RESET 4

#define PIN_BUZZER_LED_GREEN 13
#define PIN_BUZZER_LED_BLUE 12
#define PIN_BUZZER_LED_RED 11
#define PIN_BUZZER_LED_YELLOW 10
#define PIN_BUZZER_LED_WHITE 9

#define PIN_BUZZER_INPUT_GREEN 8
#define PIN_BUZZER_INPUT_BLUE 5
#define PIN_BUZZER_INPUT_RED 6
#define PIN_BUZZER_INPUT_YELLOW 7
#define PIN_BUZZER_INPUT_WHITE 10

#endif