#ifndef CONFIG_H
#define CONFIG_H

#define N_BUZZER 5

#define PIN_BUZZER_LED_GREEN 1
#define PIN_BUZZER_LED_BLUE 2
#define PIN_BUZZER_LED_RED 3
#define PIN_BUZZER_LED_YELLOW 4
#define PIN_BUZZER_LED_WHITE 5

#define PIN_BUZZER_INPUT_GREEN 6
#define PIN_BUZZER_INPUT_BLUE 7
#define PIN_BUZZER_INPUT_RED 8
#define PIN_BUZZER_INPUT_YELLOW 9
#define PIN_BUZZER_INPUT_WHITE 10

#endif